/**
 * Seed the 5 conv-26 smoke SQLite DBs (conv-26-q0..q4-smoke-ds-001) used by
 * the #63 Comunica-vs-Wazoo perf benchmark (the original DBs from the
 * smoke-ds-001 agent run were gitignored artifacts and no longer exist).
 *
 * Deterministic recipe (same on both engine trees):
 *   - conversation 26 of the LoCoMo dataset is the haystack for every
 *     conv-26-q* question; ingest it through WorldsProvider's session Turtle
 *     serializer (the exact code path the harness ingests) with extraction
 *     disabled;
 *   - import a shared facts Turtle into each container identically (the
 *     same client.import path the harness uses for extracted facts), so every
 *     DB has identical RDF content on both engine trees.
 *
 * Facts provenance (documented in the #63 artifact): the .env.smoke DeepSeek
 * key is no longer valid (HTTP 401), so instead of LLM extraction the fact
 * graph is generated by a DETERMINISTIC heuristic over the real conv-26
 * message texts (see buildConv26ClaimsTurtle): claim-style sentences from
 * each message become worlds:Claim/EventClaim nodes with claimSubject,
 * claimText, claimWhen (session year), plus schema:Event/Organization nodes.
 * This exercises the exact query surface the harness's fact-claim path hits
 * (UNION text predicates, claimSubject, NOT EXISTS Superseded, LIMIT) with
 * byte-identical content on both trees. It is NOT model output and is not
 * comparable to extraction-quality runs.
 *
 * Usage:
 *   bun run scripts/seed-conv26-smoke.ts            # main (Wazoo) tree
 *   SEED_FACTS_TTL=<shared>/conv26-facts.ttl bun run scripts/seed-conv26-smoke.ts
 *     (baseline tree: reuse the facts Turtle generated on the main tree)
 */
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { WorldsProvider } from "../src/providers/worlds"
import { LoCoMoBenchmark } from "../src/benchmarks/locomo"
import { logger } from "../src/utils/logger"

// Seeding must never extract inside ingest(): the shared facts Turtle is
// imported explicitly so both engine trees ingest byte-identical content.
process.env.EXTRACTION_PROVIDER = "none"

const RUN_SUFFIX = "smoke-ds-001"
const QUESTION_IDS = ["conv-26-q0", "conv-26-q1", "conv-26-q2", "conv-26-q3", "conv-26-q4"]
const SHARED_DIR = join(process.cwd(), "data", "bench-artifacts", "conv26-perf")
const FACTS_TTL = join(SHARED_DIR, "conv26-facts.ttl")

const benchmark = new LoCoMoBenchmark()
await benchmark.load()

const sessions = benchmark.getHaystackSessions("conv-26-q0")
if (sessions.length === 0) throw new Error("conv-26-q0 has no haystack sessions")
const sessionIds = sessions.map((s) => s.sessionId)
logger.info(`conv-26 haystack: ${sessions.length} session(s): ${sessionIds.join(", ")}`)

// Build the shared deterministic fact graph once (or reuse the provided
// one on the baseline tree), so every container — here and on the baseline
// tree — gets the identical fact bytes.
let factsTurtle: string
const factsPath = process.env.SEED_FACTS_TTL
if (factsPath) {
  factsTurtle = await readFile(factsPath, "utf-8")
  logger.info(`Reusing provided facts Turtle: ${factsPath}`)
} else {
  factsTurtle = buildConv26ClaimsTurtle(benchmark, "conv-26-q0")
  await mkdir(SHARED_DIR, { recursive: true })
  await writeFile(FACTS_TTL, factsTurtle)
  logger.info(`Generated deterministic facts Turtle: ${FACTS_TTL} (${factsTurtle.length} bytes)`)
}

const provider = new WorldsProvider()
await provider.initialize({ apiKey: process.env.DEEPSEEK_API_KEY ?? "" })

for (const questionId of QUESTION_IDS) {
  const containerTag = `${questionId}-${RUN_SUFFIX}`
  await provider.clear(containerTag)
  const t0 = performance.now()
  await provider.ingest(sessions, { containerTag })
  const client = await provider.getClientForContainer(containerTag)
  await client.import({
    source: { kind: "serialized", data: factsTurtle, contentType: "text/turtle" },
  })
  const countRes = await client.sparql({
    query: "SELECT (COUNT(*) AS ?n) WHERE { ?s ?p ?o }",
  })
  const triples =
    countRes.kind === "select" ? (countRes.data.results.bindings[0]?.n?.value ?? "?") : "?"
  logger.info(
    `Seeded ${containerTag} in ${Math.round(performance.now() - t0)}ms (${triples} triples)`
  )
}

// Sanity probe: the schema-discovery query must return rows on a fresh DB.
const client = await provider.getClientForContainer(`conv-26-q0-${RUN_SUFFIX}`)
const res = await client.sparql({
  query:
    "SELECT ?type (COUNT(*) AS ?n) WHERE { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type } GROUP BY ?type ORDER BY DESC(?n) LIMIT 20",
})
if (res.kind !== "select" || res.data.results.bindings.length === 0) {
  throw new Error("Sanity SELECT/COUNT returned no bindings after seeding")
}
logger.info(`Sanity COUNT/GROUP BY → ${res.data.results.bindings.length} types ✓`)

// ---- deterministic claim-graph generation (documented provenance above) ----

/**
 * Derives a worlds:Claim / schema:Event / schema:Organization graph from the
 * real conv-26 messages with a fixed heuristic (no LLM, no clock): every
 * message sentence containing "I " / "My " / "We " becomes one claim node
 * anchored to its session via prov:wasDerivedFrom, with claimText = the
 * sentence and claimWhen = the session's year. Superseding (every Nth claim
 * getting status Superseded) is part of the fixed pattern so the NOT EXISTS
 * filter has real selectivity.
 */
function buildConv26ClaimsTurtle(benchmark: LoCoMoBenchmark, anchorQuestionId: string): string {
  const sessions = benchmark.getHaystackSessions(anchorQuestionId)
  const lines: string[] = [
    "# Deterministic conv-26 claim graph for the #63 perf benchmark.",
    "# Provenance: heuristic over LoCoMo conversation 26 message texts (no LLM).",
    "",
  ]
  const seenSpeakers = new Set<string>()
  const seenOrgs = new Set<string>()
  let claimIdx = 0
  for (const session of sessions) {
    const sessionUri = `urn:session:${session.sessionId}`
    const date = String(session.metadata?.formattedDate ?? session.metadata?.date ?? "unknown")
    const yearMatch = date.match(/(\d{4})/)
    const when = yearMatch ? yearMatch[1]! : "unknown"

    for (const [idx, msg] of session.messages.entries()) {
      // Message text is already the escaped single-line form the session
      // serializer builds; split on sentence enders like it.
      const text = String(msg.content)
      const sentences = text.split(/(?<=[.!?])\s+/).filter(Boolean)
      for (const sentence of sentences) {
        const isClaimish = /^(I|My|We|I'm|I've|I'll)\b/.test(sentence)
        if (!isClaimish) continue
        claimIdx += 1
        const claimUri = `${sessionUri}/claim/${idx}`
        const kind = claimIdx % 5 === 0 ? "EventClaim" : "FactClaim"
        lines.push(
          `<${claimUri}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://worlds.wazoo.dev/ns/memory#${kind}> .`,
          `<${claimUri}> <https://worlds.wazoo.dev/ns/memory#claimText> "${escapeTtl(sentence)}" .`,
          `<${claimUri}> <https://worlds.wazoo.dev/ns/memory#claimSubject> "${escapeTtl(String(msg.speaker ?? ""))}" .`,
          `<${claimUri}> <https://worlds.wazoo.dev/ns/memory#claimWhen> "${when}" .`,
          `<${claimUri}> <http://www.w3.org/ns/prov#wasDerivedFrom> <${sessionUri}> .`
        )
        // Fixed supersede pattern: every 7th claim is superseded so the
        // harness's FILTER NOT EXISTS has real selectivity.
        if (claimIdx % 7 === 0) {
          lines.push(
            `<${claimUri}> <https://worlds.wazoo.dev/ns/memory#status> <https://worlds.wazoo.dev/ns/memory#Superseded> .`
          )
        }
        // EventClaim branches additionally project a schema:Event domain node
        // (name = the sentence, about the speaker) so the multi-hop
        // Event→Person join query has its intended domain data. Per-message
        // Person/Organization nodes keep the schema-discovery counts realistic.
        if (kind === "EventClaim") {
          const eventUri = `${sessionUri}/event/${idx}`
          lines.push(
            `<${eventUri}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Event> .`,
            `<${eventUri}> <http://schema.org/name> "${escapeTtl(sentence)}" .`,
            `<${eventUri}> <http://schema.org/about> <${sessionUri}/person/${idx}> .`,
            `<${eventUri}> <http://schema.org/startDate> "${when}" .`,
            `<${eventUri}> <http://www.w3.org/ns/prov#wasDerivedFrom> <${sessionUri}> .`,
            `<${sessionUri}/person/${idx}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .`,
            `<${sessionUri}/person/${idx}> <http://schema.org/name> "${escapeTtl(String(msg.speaker ?? ""))}" .`
          )
        }
        if (msg.speaker && !seenSpeakers.has(msg.speaker)) {
          seenSpeakers.add(msg.speaker)
          const personUri = `urn:person:${sanitize(msg.speaker)}`
          lines.push(
            `<${personUri}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .`,
            `<${personUri}> <http://schema.org/name> "${escapeTtl(msg.speaker)}" .`
          )
        }
        const orgMatch = sentence.match(/(?:at|for|join)\s+([A-Z][A-Za-z& ]{2,40})/)
        if (orgMatch?.[1]) {
          const orgName = orgMatch[1].trim()
          const orgUri = `urn:org:${sanitize(orgName)}`
          if (!seenOrgs.has(orgUri)) {
            seenOrgs.add(orgUri)
            lines.push(
              `<${orgUri}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Organization> .`,
              `<${orgUri}> <http://schema.org/name> "${escapeTtl(orgName)}" .`
            )
          }
        }
      }
    }
  }
  return lines.join("\n")
}

function escapeTtl(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")
}

function sanitize(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]+/g, "-")
}
